name: flutter_forge
description: >
  A robust opinionated framework for building state based applications in a
  modular, testable, and composable style.
version: 0.2.0
homepage: https://github.com/uptech/flutter_forge
repository: https://github.com/uptech/flutter_forge

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
