#!/usr/bin/env zsh

scripts_path=${0:a:h}

source "$scripts_path/../.git-ps/vendor/libs/fvm_patch.zsh"
source "$scripts_path/../.git-ps/vendor/libs/messaging.zsh"
source "$scripts_path/../.git-ps/vendor/libs/general.zsh"

# Update dependencies based on any changes in the pubspec.yaml

echo "\n\nRunning flutter pub get..."
time fvm flutter pub get
exit_nonzero $? "fvm flutter pub get failed" 20

# Make sure format is good

echo "\n\nRunning dart format --set-exit-if-changed..."
time fvm dart format --set-exit-if-changed .
exit_nonzero $? "Running dart format --set-exit-if-changed failed" 30

# Make sure code is good

echo "\n\nRunning flutter analyze..."
time fvm flutter analyze .
exit_nonzero $? "Running flutter analyze failed" 80

exit 0
