name: Flutter CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  Run-Test-Suite:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh
          
      - name: Checkout Source Code
        id: checkout-source-code
        uses: actions/checkout@v3
      
      - name: Setup FVM 
        id: setup-fvm
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Setup Flutter Environment
        id: setup-flutter-environment
        uses: subosito/flutter-action@v2  
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Build (Dev)
        id: build-dev
        shell: zsh {0}
        run: ./scripts/build

      - name: Run full test suite
        id: run-full-test-suite
        shell: zsh {0}
        run: flutter test
